import pandas as pd
import numpy as np
authors = pd.read_csv('authors.csv')
avg_ratings = pd.read_csv('avg_ratings.csv')
awards = pd.read_csv('awards.csv')
genres = pd.read_csv('genres.csv')
pages = pd.read_csv('pages.csv')
places = pd.read_csv('places.csv')
publishes = pd.read_csv('publishes.csv')
ratings = pd.read_csv('ratings.csv')
reviews = pd.read_csv('reviews.csv')
series = pd.read_csv('series.csv')
titles = pd.read_csv('titles.csv')
url = pd.read_csv('urls.csv')
urls = url.head(1000)
genres1 = genres.replace('ERROR HERE!!!!!!!!!!, ERROR HERE!!!!!!!!!!, ERROR HERE!!!!!!!!!!', '')
print(genres1)
series1 = series.replace({False: 0, True: 1})
print(series1)
Data = pd.concat([urls, titles, authors, reviews, ratings, avg_ratings, pages, publishes, series1, genres1, awards, places],  axis=1)
print(Data)
Data.to_csv(r'C:\Users\ziolo\PycharmProjects\BuildWeek\Data.csv', index=False)